### ISSUE TITLE
Error: queueLoad failed

### ISSUE THREAD

**Issue by manne01** [angelnu/ioBroker.chromecast#32]
Hi there,

trying to set url2play i get:

_chromecast.0 2018-03-16 08:56:56.329	error	room1 - Cannot play file "http://www.egofm.de/stream/192kb.m3u": Error: queueLoad failed
chromecast.0	2018-03-16 08:56:56.329	error	at Client.emit (events.js:182:7)
chromecast.0	2018-03-16 08:56:56.329	error	at emitMany (events.js:113:20)
chromecast.0	2018-03-16 08:56:56.329	error	at Client.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/node_modules/castv2/lib/channel.js:23:10)
chromecast.0	2018-03-16 08:56:56.329	error	at Channel.emit (events.js:172:7)
chromecast.0	2018-03-16 08:56:56.329	error	at emitTwo (events.js:87:13)
chromecast.0	2018-03-16 08:56:56.329	error	at Channel.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/controller.js:16:10)
chromecast.0	2018-03-16 08:56:56.329	error	at MediaController.emit (events.js:172:7)
chromecast.0	2018-03-16 08:56:56.329	error	at emitTwo (events.js:92:20)
chromecast.0	2018-03-16 08:56:56.329	error	at MediaController.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
chromecast.0	2018-03-16 08:56:56.329	error	at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/media.js:149:23
chromecast.0	2018-03-16 08:56:56.329	error	room1- Error playing playlist - Error: queueLoad failed_

On some other try to play it stated only this:

_chromecast.0	2018-03-16 09:59:35.521	error	room1- Cannot play file "http://www.egofm.de/stream/192kb.m3u": Error: queueLoad failed
chromecast.0	2018-03-16 09:59:35.518	error	room1- Error playing playlist - Error: queueLoad failed at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/_

I restarted the adapter multiple times. I restarted my device. I got more devices, and they all behave the same. I tried on 1.3.5 and latest 1.4.2 - same thing.

Could you add some more information about the error reason?
kind regards
Manfred

**Comment by manne01** [comment]
I just found out that the reason is that is wont play this kind streams:

http://www.egofm.de/stream/192kb.m3u
or
http://www.egofm.de/stream/128kb.m3u

But these URLs worked already in my iobroker chromecast environment! And other players and browsers still do play this streams!

And on my iobroker chromecast adapter other stream sources work without problem!e.g. http://mp3-live.swr3.de/swr3_m.m3u or http://stream.klassikradio.de/smooth/mp3-192

I compared them already with VLC player media/codec information, coulnd find something obvious.

Tried other streams for the same radio station:
This stream represents the same radio station and works like a charm - no error message here:
http://mp3ad.egofm.c.nmdn.net/egofm_192/livestream.mp3

Can you please check on your side?

**Comment by angelnu** [comment]
Ok, I debugged the http://www.egofm.de/stream/192kb.m3u URL and found four issues:

- the code detecting the media type based in the URL had a bug and did not do anything -> fixed in the castv2-player library
- the http://www.egofm.de/stream/192kb.m3u is a redirect to the mp3 file. IMO this is not valid -> an URL ending  in .m3u should be a playlist.
- the icy module I use is a wrapper of http that does not follow redirects -> I will need to write a piece of code to follow redirects
- chromecast do not like http with redirect - this will handled once I "pre-process" the URL before sending it to the Chromecast

For the time being the circumvention is to use the redirect target in url2play: http://mp3ad.egofm.c.nmdn.net/egofm_192/livestream.mp3

**Comment by angelnu** [comment]
@manne01 - Please try version 1.4.3 (github only for now)

**Comment by manne01** [comment]
Thank you for checking this. I just installed 1.4.3 and tried playing http://www.egofm.de/stream/192kb.m3u but still get:

error JBLPlaylist - Cannot play file " http://www.egofm.de/stream/192kb.m3u": Error: ENOENT: no such file or directory, open ' http://www.egofm.de/stream/192kb.m3u'

or even


chromecast.0 | 2018-04-08 10:12:31.863 | error | JBLPlaylist - Cannot play file "http://www.egofm.de/stream/192kb.m3u": Error: queueLoad failed
-- | -- | -- | --
chromecast.0 | 2018-04-08 10:12:31.860 | error | at Client.emit (events.js:182:7)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at emitMany (events.js:113:20)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at Client.onmessage  (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/node_modules/castv2/lib/channel.js:23:10)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at Channel.emit (events.js:172:7)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at emitTwo (events.js:87:13)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at Channel.onmessage  (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/controller.js:16:10)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at MediaController.emit (events.js:172:7)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at emitTwo (events.js:92:20)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at MediaController.onmessage  (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
chromecast.0 | 2018-04-08 10:12:31.860 | error | at  /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/media.js:149:23
chromecast.0 | 2018-04-08 10:12:31.860 | error | JBLPlaylist - Error playing playlist - Error: queueLoad failed
chromecast.0 | 2018-04-08 10:12:30.998 | info | JBLPlaylist - Try to play playlist with 1 items
chromecast.0 | 2018-04-08 10:12:30.925 | info | JBLPlaylist - Try to play url - http://www.egofm.de/stream/192kb.m3u


I am sorry! Could it be differences in our environments?

**Comment by angelnu** [comment]
Could you please check the version of the `castv2-player`library at /opt/iobroker/node_modules/castv2-player/package.json ? It should be 1.1.12 for it to work.

When I try to play your URL I get:

```
2018-04-08 19:05:19.324  - [32minfo[39m: chromecast.0 audioBedroom - Try to play url - http://www.egofm.de/stream/192kb.m3u
2018-04-08 19:05:19.337  - [32minfo[39m: chromecast.0 audioBedroom - Try to launch default player
2018-04-08 19:05:19.445  - [32minfo[39m: chromecast.0 audioBedroom - Detected redirection (301) to https://www.egofm.de/stream/192kb.m3u
2018-04-08 19:05:19.539  - [32minfo[39m: chromecast.0 audioBedroom - Detected redirection (302) to http://mp3ad.egofm.c.nmdn.net/egofm_192/livestream.mp3
2018-04-08 19:05:20.145  - [32minfo[39m: chromecast.0 audioBedroom - Try to join player
2018-04-08 19:05:20.147  - [32minfo[39m: chromecast.0 audioBedroom - Connected player
2018-04-08 19:05:20.148  - [32minfo[39m: chromecast.0 audioBedroom - Player joint
2018-04-08 19:05:20.148  - [32minfo[39m: chromecast.0 audioBedroom - Connected player
2018-04-08 19:05:20.149  - [32minfo[39m: chromecast.0 audioBedroom - Default player lauched
2018-04-08 19:05:20.181  - [32minfo[39m: chromecast.0 audioBedroom - Try to play playlist with 1 items
2018-04-08 19:05:21.459  - [32minfo[39m: chromecast.0 audioBedroom - Playing playlist with 1 items
2018-04-08 19:05:23.499  - [32minfo[39m: chromecast.0 audioBedroom - Playing - http://mp3ad.egofm.c.nmdn.net/egofm_192/livestream.mp3
```

**Comment by manne01** [comment]
I checked the version today. The lib is in /opt/iobroker/node_modules/castv2-player/ and the file package.json shows Version 1.1.12 so I guess this is correct.

Checked to play http://www.egofm.de/stream/192kb.m3u again, and -> it works and I have "your" log entries! I guess there was some restart or something missing before. 

Great - thanks!!!

**Comment by hubermedia** [comment]
hey!

i got a intersting problem. both m3u files are identical but only on two different urls:

working:
http://streams.br.de/bayern3_2.m3u

not working:
http://services.hubermedia.de/partner/privat/playlist.m3u

here the error:

chromecast.0 | 2020-01-01 11:50:46.477 | error | (878) Badezimmer_OG - Cannot play file "http://services.hubermedia.de/partner/privat/playlist2.m3u": Error: queueLoad failed
-- | -- | -- | --
chromecast.0 | 2020-01-01 11:50:46.476 | error | at TLSSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at PacketStreamWrapper.emit (events.js:198:13)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at PacketStreamWrapper.onpacket (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2/lib/client.js:81:10)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at Client.emit (events.js:203:15)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at Client.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2/lib/channel.js:23:10)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at Channel.emit (events.js:198:13)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at Channel.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/controller.js:16:10)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at fn.emit (events.js:203:15)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at fn.onmessage (/opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
chromecast.0 | 2020-01-01 11:50:46.476 | error | at /opt/iobroker/node_modules/iobroker.chromecast/node_modules/castv2-client/lib/controllers/media.js:149:23
chromecast.0 | 2020-01-01 11:50:46.476 | error | (878) Badezimmer OG - Error playing playlist - Error: queueLoad failed




any idea how i can fix this? i would like to create a simple playlist with several iradio stations in one m3u file.

thx
stefan
